### ISSUE TITLE
command failure can be overlooked

### ISSUE THREAD

**Issue by ryok-0319** [kenjiszk/ecs_task_executor#1]
https://github.com/kenjiszk/ecs_task_executor/blob/master/ecs_task_executor.go#L101

Containers の順番は可変なので、Containers[0] でコマンドが実行されているとは限らない

例えば、Containers[1] でコマンドが実行されていて、code 1 で exit （失敗）したが、Containers[0] は code 0 で exit して成功扱いになってしまう場合がある

**Comment by kenjiszk** [comment]
opts.Name でフィルターすればokですね、直します。
